# render.yaml
services:
  - type: web
    name: mi-that-groq
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python mi_that_groq.py"
    pythonVersion: 3.11.9
    region: oregon
